---
- name: Создание папки TEST на Windows-компьютере
  hosts: dc01
  gather_facts: false

  tasks:
    - name: Создание папки TEST на диске C
      win_file:
        path: C:\TEST
        state: directory
      delegate_to: 192.168.72.160
